name: Automated test
permissions:
  contents: read
  
on:
  push:
    branches: [ "master" ]

jobs:
  Linux_x86-64_GCC:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build angelscript
      run: |
        cd $GITHUB_WORKSPACE/sdk/angelscript/projects/gnuc
        export "CXXFLAGS=-O2"
        make
    - name: build test_feature
      run: |
        cd $GITHUB_WORKSPACE/sdk/tests/test_feature/projects/gnuc
        make
    - name: run test_feature
      run: |
        cd $GITHUB_WORKSPACE/sdk/tests/test_feature/bin
        ./testgnuc

  Linux_x86-64_GCC_AS_DEBUG:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build angelscript
      run: |
        cd $GITHUB_WORKSPACE/sdk/angelscript/projects/gnuc
        export "CXXFLAGS=-DAS_DEBUG -O0"
        make
    - name: build test_feature
      run: |
        cd $GITHUB_WORKSPACE/sdk/tests/test_feature/projects/gnuc
        make
    - name: run test_feature
      run: |
        cd $GITHUB_WORKSPACE/sdk/tests/test_feature/bin
        ./testgnuc
        
  Windows_x86-64_Clang:      
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
       version: latest
       platform: x64
       cc: 1
    - name: build angelscript & test_feature
      shell: powershell
      run: |
        cd $env:GITHUB_WORKSPACE/sdk/tests/test_feature/projects/cmake
        cmake . -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
        cmake --build . --config Release
    - name: run test_feature
      shell: powershell
      run: |
        cd $env:GITHUB_WORKSPACE/sdk/tests/test_feature/bin
        ./test_feature.exe

  Windows_x86_Clang-Cl:      
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86]
    env:
      VCPKG_BUILD_TYPE: release
      VCPKG_DEFAULT_TRIPLET:  ${{ matrix.arch == 'amd64' && 'x64-windows' || 'x86-windows' }}        
    steps:
    - uses: actions/checkout@v4
    - name: set up Clang
      uses: ilammy/msvc-dev-cmd@v1
    - name: build angelscript & test_feature
      run: |
        cd ${{github.workspace}}/sdk/tests/test_feature/projects/cmake
        cmake . -G Ninja -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
    - name: run test_feature
      run: |
        cd ${{github.workspace}}/sdk/tests/test_feature/bin
        ./test_feature.exe

  MacOS_arm64_Clang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: build angelscript & test_feature
      run: |
        cd $GITHUB_WORKSPACE/sdk/tests/test_feature/projects/cmake
        cmake .
        cmake --build .
    - name: run test_feature
      run: |
        cd $GITHUB_WORKSPACE/sdk/tests/test_feature/bin
        ./test_feature
        


        
